version: '2'
services:
  db:
    image: postgres:10.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'dbuser'
      POSTGRES_PASSWORD: 'dbpassword'
      POSTGRES_DB: 'dbname'